using System;
using System.Collections.Generic;
using Microsoft.Xna.Framework;

namespace BlossomTales2.Randomizer.mm
{
    public class OverworldNorth : Region
    {
        public override Predicate<Inventory> CanAccess => inventory => World.OverworldWest.CanAccess(inventory) && inventory.HasGrappleHook ||
                                                                       World.OverworldEast.CanAccess(inventory) && (inventory.HasBoomerang || inventory.HasGrappleHook);

        public OverworldNorth(World world) : base("Northern Overworld", world)
        {
            Locations = new List<Location>
            {
                //Note caves
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(384f, 0f, 208f)),
                "Note Cave Top Left Chest",
                inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(512f, 0f, 208f)),
                    "Note Cave Top Middle Chest",
                    inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(640f, 0f, 208f)),
                    "Note Cave Top Right Chest",
                    inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(384f, 0f, 336f)),
                    "Note Cave Lower Left Chest",
                    inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(512f, 0f, 336f)),
                    "Note Cave Lower Middle Chest",
                    inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-19x16-noteCave.tmx", "Chest_Small", new Vector3(640f, 0f, 336f)),
                    "Note Cave Lower Right Chest",
                    inventory => inventory.CanOpenNoteDoor && inventory.CanSwitchLevers && (inventory.HasBombs || inventory.CanCraftPotion(ItemType.Jar_Speedster)),
                    ItemType.GoldCoin),
                //Caves
                new Location(new LocationId("overworld-20x17-cave.tmx", "Chest_Small", new Vector3(608f, 0f, 232f)),
                    "Fishing Hole Cave Chest",
                    _ => true,
                    ItemType.HeartQ_1),
                new Location(new LocationId("overworld-21x17-cave.tmx", "Chest_Small", new Vector3(384f, 0f, 320f)),
                    "Wizard Bomb Cave Top Left Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17-cave.tmx", "Chest_Small", new Vector3(576f, 0f, 320f)),
                    "Wizard Bomb Cave Top Right Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17-cave.tmx", "Chest_Small", new Vector3(288f, 0f, 512f)),
                    "Wizard Bomb Cave Lower Left Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17-cave.tmx", "Chest_Small", new Vector3(480f, 0f, 512f)),
                    "Wizard Bomb Cave Lower Middle Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17-cave.tmx", "Chest_Small", new Vector3(672f, 0f, 512f)),
                    "Wizard Bomb Cave Lower Right Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x18-cave.tmx", "Chest_Small", new Vector3(480f, 0f, 324f)),
                    "River Bomb Cave Top Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x18-cave.tmx", "Chest_Small", new Vector3(480f, 0f, 324f)),
                    "River Bomb Cave Top Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x18-cave.tmx", "Chest_Small", new Vector3(384f, 0f, 480f)),
                    "River Bomb Cave Lower Left Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x18-cave.tmx", "Chest_Small", new Vector3(576f, 0f, 480f)),
                    "River Bomb Cave Lower Right Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16-cave.tmx", "Chest_Small", new Vector3(1408f, 0f, 1536f)),
                    "Waterfall Cave Top Left Chest",
                    inventory => inventory.HasFlipper && inventory.HasGrappleHook && (inventory.HasBow || inventory.HasBoomerang || inventory.HasSwordBeams),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16-cave.tmx", "Chest_Small", new Vector3(1600f, 0f, 1536f)),
                    "Waterfall Cave Top Right Chest",
                    inventory => inventory.HasFlipper && inventory.HasGrappleHook && (inventory.HasBow || inventory.HasBoomerang || inventory.HasSwordBeams),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16-cave.tmx", "Chest_Small", new Vector3(1408f, 0f, 1664f)),
                    "Waterfall Cave Lower Left Chest",
                    inventory => inventory.HasFlipper && inventory.HasGrappleHook && (inventory.HasBow || inventory.HasBoomerang || inventory.HasSwordBeams),
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16-cave.tmx", "Chest_Small", new Vector3(1600f, 0f, 1664f)),
                    "Waterfall Cave Lower Right Chest",
                    inventory => inventory.HasFlipper && inventory.HasGrappleHook && (inventory.HasBow || inventory.HasBoomerang || inventory.HasSwordBeams),
                    ItemType.GoldCoin),
                //Items npc
                new Location(new LocationId("overworld-19x16.tmx", "treeLordGiftAcorns", Vector3.Zero),
                    "Tree Lord Acorns",
                    _ => true,
                    ItemType.TreeSeed),
                //Long side quests
                new Location(new LocationId("overworld-19x16.tmx", "treeLordReward", Vector3.Zero),
                    "Tree Lord Reward",
                    inventory => inventory.HasPlantedAllSeeds,
                    ItemType.HeartQ_1),
                new Location(new LocationId("overworld-19x17.tmx", "queenBee", Vector3.Zero),
                    "Tree Lord Reward",
                    inventory => inventory.HasCollectedAllHoneycombs,
                    ItemType.BeeMedallion),
                //bardes
                new Location(new LocationId("overworld-20x16.tmx", "bard_song", Vector3.Zero),
                    "Forest Bard",
                    inventory => inventory.CanDoDamage,
                    ItemType.SummonBalloon),
                //mausoleum
                new Location(new LocationId("overworld-20x16-combat.tmx", "Chest_Small", new Vector3(416f, 0f, 2084f)),
                    "Forest Combat Mausoleum",
                    inventory => inventory.CanDoDamage,
                    ItemType.CombatScroll),
                //Chests
                new Location(new LocationId("forestMaze-end.tmx", "Chest_Small", new Vector3(560f, 0f, 308f)),
                    "Forest Maze Left Chest",
                    _ => true,
                    ItemType.HeartQ_1),
                new Location(new LocationId("forestMaze-end.tmx", "Chest_Small", new Vector3(724f, 0f, 308f)),
                    "Forest Maze Right Chest",
                    _ => true,
                    ItemType.GoldCoin), //TODO:Large coin amount
                new Location(new LocationId("overworld-19x17.tmx", "Chest_Small", new Vector3(2168f, 0f, 1600f)),
                    "Bee Area Rock Bomb Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-20x17.tmx", "Chest_Small", new Vector3(376f, 0f, 1480f)),
                    "Fishing Hole Rock Bomb Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-20x17.tmx", "Chest_Small", new Vector3(2348f, 0f, 168f)),
                    "Fishing Hole Ledge Chest",
                    inventory => inventory.HasBombs,
                    ItemType.Honeycomb),
                new Location(new LocationId("overworld-21x16.tmx", "Chest_Small", new Vector3(2168f, 0f, 276f)),
                    "Forest Ledge Chest",
                    inventory => inventory.HasBoomerang,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17.tmx", "Chest_Small", new Vector3(1468f, 0f, 972f)),
                    "Wizard Rock Bomb Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-21x17-wizHouse.tmx", "Chest_Small", new Vector3(956f, 0f, 128f)),
                    "Wizard House Chest",
                    _ => true,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16.tmx", "Chest_Small", new Vector3(824f, 0f, 2452f)),
                    "Pedestal Buried Chest",
                    inventory => inventory.HasShovel,
                    ItemType.GoldCoin),
                new Location(new LocationId("overworld-22x16.tmx", "SwordInStone", new Vector3(0f, 0f, 0f)),
                    "Pedestal",
                    inventory => inventory.HasFlipper && inventory.CanLiftMasterSword,
                    ItemType.Sword),
                new Location(new LocationId("overworld-22x17.tmx", "Chest_Small", new Vector3(684f, 0f, 2104f)),
                    "Construction Bridge Rock Bomb Chest",
                    inventory => inventory.HasBombs,
                    ItemType.GoldCoin),
            };
        }
    }
}
